export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FALI';

export const CREATE_WORK_CENTER = 'CREATE_WORK_CENTER';
export const CREATE_ITEM = 'CREATE_ITEM';
export const CREATE_ORDER = 'CREATE_ORDER';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_WORK_CENTER = 'EDIT_WORK_CENTER';
export const EDIT_ITEM = 'EDIT_ITEM';
export const EDIT_ORDER = 'CEDIT_ORDER';
export const GET_WORK_CENTERS = 'GET_WORK_CENTERS';
export const LOGIN_USER = 'LOGIN_USER';

export const GET_LIST_OF_USERS = 'GET_LIST_OF_USERS';
