const CREATE_USER = 'CREATE_USER';
const CREATE_WORK_CENTER = 'CREATE_WORK_CENTER';
const CREATE_ITEM = 'CREATE_ITEM';
const CREATE_ORDER = 'CREATE_ORDER';
const EDIT_USER = 'EDIT_USER';
const EDIT_WORK_CENTER = 'EDIT_WORK_CENTER';
const EDIT_ITEM = 'EDIT_ITEM';
const EDIT_ORDER = 'CEDIT_ORDER';

export {
  CREATE_USER,
  CREATE_WORK_CENTER,
  CREATE_ITEM,
  CREATE_ORDER,
  EDIT_USER,
  EDIT_WORK_CENTER,
  EDIT_ITEM,
  EDIT_ORDER,
};
