export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
//
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FALI';
//
export const CREATE_ITEM = 'CREATE_ITEM';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAIL = 'CREATE_ITEM_FAIL';
//
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
//
export const LOGOUT_USER = 'LOGOUT_USER';
//
export const CREATE_WORK_CENTER = 'CREATE_WORK_CENTER';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_WORK_CENTER = 'EDIT_WORK_CENTER';
export const EDIT_ITEM = 'EDIT_ITEM';
export const EDIT_ORDER = 'EDIT_ORDER';
export const GET_WORK_CENTERS = 'GET_WORK_CENTERS';

export const GET_LIST_OF_USERS = 'GET_LIST_OF_USERS';
export const GET_LIST_OF_ITEMS = 'GET_LIST_OF_ITEMS';
export const GET_LIST_OF_ORDERS = 'GET_LIST_OF_ORDERS';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const TAKE_ORDER_IN_WORK = 'TAKE_ORDER_IN_WORK';
export const GET_ORDER_IN_WORK = 'GET_ORDER_IN_WORK';
